import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{ display: 'flex', justifyContent: 'flex-end', gap: 16, padding: 16 }}>
          {session?.user ? (
            <>
              <span style={{ color: '#3f9b0b', fontWeight: 600 }}>
                {session.user.name || session.user.email}
              </span>
              <form action="/api/auth/signout" method="post">
                <button className="btn" type="submit">Cerrar sesión</button>
              </form>
            </>
          ) : (
            <Link href="/api/auth/signin">
              <button className="btn">Iniciar sesión</button>
            </Link>
          )}
        </header>
        {children}
      </body>
    </html>
  );
}
